### ISSUE TITLE
support for protoc/protobuf-java 4?

### ISSUE THREAD

**Issue by pjfanning** [scalapb/protoc-bridge#384]
Would it be possible to release a version of this lib that supports the latest protoc/protobuf-java version (4.28.x)?

Thanks for your work on this lib. It is much appreciated.

I tried scalapb 1.0.0.alpha1 but got compile problems and I suspect that it might be related to sbt-protoc and this lib.

**Comment by thesamet** [comment]
Can you provide the issue you had with 1.0.0.alpha.1 . Have you set `Compile / PB.protocVersion` to the version of protoc you want to use?

**Comment by pjfanning** [comment]
Thanks @thesamet for the quick response.

The issue I am seeing is in Apache Pekko gRPC. My PR is https://github.com/apache/pekko-grpc/pull/371

The pekko-grpc build does set the PB.protocVersion.

I am seeing compile issues because generated code will not compile.

**Comment by thesamet** [comment]
I think protoc-bridge does not need to be updated as it works as the tests for ScalaPB 1.0.0-alpha.1 using protobuf-4 pass with the current version. Briefly looking at the error messages at the linked issue, I think the pekko-grpc project mixes a few versions of protobuf-java right now.

**Comment by pjfanning** [comment]
The build for Pekko gRPC is pretty complicated and the main part of the build that uses your ScalaPB tooling seems to be working ok. It is some later integration testing that is failing and that is probably unrelated to your tools. I'll look into it. Thanks for your time.
