### ISSUE TITLE
Remove dependency on Python

### ISSUE THREAD

**Issue by augi** [scalapb/protoc-bridge#9]
Python is not something that is installed on each Windows computer so this library has a _hidden_ dependency.

Isn't it possible to rewrite [WindowsPluginFrontend](https://github.com/scalapb/protoc-bridge/blob/master/src/main/scala/protocbridge/frontend/WindowsPluginFrontend.scala) without Python usage?

If I understand the problem correctly, we could add a simple Golang program to `resources` and then just call the prepared binaries. Golang binaries are standalone so the project wouldn't have dependency on Python.

Are you willing to accept this kind of PR?

**Comment by thesamet** [comment]
Yeah, I'm happy to get rid of this dependency. Would it be possible to cross-compile the golang binaries for Windows on a Linux machine? (I prefer to have the entire build/release scripted).

Another alternative is to implement it in Java since it's safe to assume that a JVM is available already.

**Comment by augi** [comment]
My original idea was to create a standalone GitHub project that would produce the golang binaries for all platform. Then protoc-bridge would just use these binaries (in similar fashion as `scalapbc` uses `protoc`).

But I like your idea! What do you mean, would it be possible to add entrypoint (`main` method) to this library and so execute itself? So just span another JVM instance. In this case, I'm not sure if performance wouldn't be problem (because of JVM startup).

**Comment by thesamet** [comment]
Right, add another class with a static `main` method and have the JVM launch another one. I think that since that single class file is going to not have any dependencies then start time wouldn't be too bad, though probably not as fast as go.

**Comment by thesamet** [comment]
I think we can close this issue. This has been working well for over a year now.

**Comment by augi** [comment]
Agree, thanks!
